### ISSUE TITLE
Implement `.filter`

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/bluebird-api#11]

**Comment by BnayaZil** [comment]
mine

**Comment by noamkatzir** [comment]
I will take this

**Comment by benjamingr** [comment]
@noamkatzir status?

**Comment by noamkatzir** [comment]
Need to sit on it, probably this Wednesday

**Comment by benjamingr** [comment]
I'm stealing it then, would love your help on some of the other issues.

**Comment by benjamingr** [comment]
Closed with https://github.com/benjamingr/bluebird-api/commit/4af01a5cbf9c6e85bccdbbf3c9b60914443fd0ad
