### ISSUE TITLE
Add tests to .spread

### ISSUE THREAD

**Issue by MadaraUchiha** [benjamingr/bluebird-api#19]
After the following have been implemented:

- `.all()`
- `.defer()`
- `.caught()`

**Comment by benjamingr** [comment]
defer is not going to be implemented and caught is just catch for IE6 and can be replaced

**Comment by benjamingr** [comment]
@MadaraUchiha status?

**Comment by MadaraUchiha** [comment]
Haven't worked on it since the meetup. Might be able to continue today, if not, tomorrow.

**Comment by benjamingr** [comment]
.all and .defer are implemented, `.caught` is just `.catch`. Cheers.

**Comment by luggage66** [comment]
.caught() is already aliased.

**Comment by luggage66** [comment]
Stolen, with permission, from @MadaraUchiha
