### ISSUE TITLE
Implement `.delay`

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/bluebird-api#26]

**Comment by Shrulik** [comment]
Will take this one.

**Comment by benjamingr** [comment]
@Shrulik status?

**Comment by Shrulik** [comment]
I actually finished that on Wedenesday, but I wanted to finish .timeout as well, as their tests are combined in bluebird, and didn't have time this weekend. I will look into it now for a bit.

**Comment by benjamingr** [comment]
Great, thanks @Shrulik - let me know if you have any issues. 

Note that it also requires implementing a TypeError subclass, see how I did `OperationalError` or `
AggregateError`

**Comment by Shrulik** [comment]
Yeha, I did my own TimeoutError, will switch to your way.

I think there is a bug with thenReturn #39 . It doesn't preserve promise rejection.
Bluebird : http://jsfiddle.net/mpo4yrmu/122/
Test case for us :         Promise.reject(10).thenReturn(100).then(function (la) {
            console.log('ThenReturn Causes success')
        }, ()=>{
            console.log('ThenReturn retains failure');
        })

I will try to look into it tomorrow.

**Comment by benjamingr** [comment]
thenReturn looks wrong. Will fix

**Comment by benjamingr** [comment]
Fixed in https://github.com/benjamingr/bluebird-api/commit/1aa9e5e5999b68f1fde427a28812f29664bedfbc - sorry.
