### ISSUE TITLE
Implement .bind

### ISSUE THREAD

**Issue by benjamingr** [benjamingr/bluebird-api#3]

**Comment by noamkatzir** [comment]
I will take it

**Comment by noamkatzir** [comment]
not needed duo to arrow function

**Comment by benjamingr** [comment]
Agree, closing.

**Comment by luggage66** [comment]
I tried to use bluebird-api in my own code, just to see, and .bind() was the first thing I ran into. While I don't use .bind() too much (just some old code) and refactoring it out is not that big of a deal, I think others could run into the same thing.

If having arrow functions mean we don't need .bind(), then having destructuring means we don't need .spread(). Except for compatibility...

I'm not sure where the line is drawn between being compatible and being redundant.

**Comment by benjamingr** [comment]
@luggage66 `.bind` is cross-implementation and doing it right is risky. We can warn on `bind` indicating where it is and how to fix it.

**Comment by benjamingr** [comment]
@luggage66 how do you feel about this now?

**Comment by luggage66** [comment]
I concede your point about it being annoying to do and shouldn't be needed with modern es6 code. Closing issue. I may still poke around and see if I can come up with any clever ideas to implement it, but... meh.
